# Generated by Django 5.2.5 on 2025-08-30 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_result_html_calculationresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationresult',
            name='input_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
