# Generated by Django 5.2.5 on 2025-08-30 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_calculationresult_input_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calculationresult',
            options={'ordering': ['-created_at']},
        ),
    ]
